### ISSUE TITLE
Blank space

### ISSUE THREAD

**Issue by aayush1408** [prankurverma/resume#1]
Don't you think, blank space present on the left side of the resume should be removed. I think the **Skills** and **Other Information** section can cover the whole width of the page, or you can add other details. Else everything seems perfect to me.

**Comment by prankurverma** [comment]
The page stretches to dimensions of an A4 sheet and can be printed on A4 anytime, so this is the reason for those blank spaces. And for the latter, I would be adding more prof. details so I left space for that.
